
-- Run once as ACCOUNTADMIN. Creates the role hierarchy so future
-- steps (Airflow load, dbt transform) never need ACCOUNTADMIN.


USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ERCOT_ADMIN;
CREATE ROLE IF NOT EXISTS ERCOT_LOADER;
CREATE ROLE IF NOT EXISTS ERCOT_TRANSFORMER;

GRANT USAGE ON WAREHOUSE WAREHOUSE_CONNECT TO ROLE ERCOT_ADMIN;
GRANT USAGE ON WAREHOUSE WAREHOUSE_CONNECT TO ROLE ERCOT_LOADER;
GRANT USAGE ON WAREHOUSE WAREHOUSE_CONNECT TO ROLE ERCOT_TRANSFORMER;

GRANT USAGE ON DATABASE AWS_SNOWFLAKE_PIPELINE TO ROLE ERCOT_ADMIN;
GRANT USAGE ON DATABASE AWS_SNOWFLAKE_PIPELINE TO ROLE ERCOT_LOADER;
GRANT USAGE ON DATABASE AWS_SNOWFLAKE_PIPELINE TO ROLE ERCOT_TRANSFORMER;

GRANT USAGE ON SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_ADMIN;
GRANT USAGE ON SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_LOADER;
GRANT USAGE ON SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_TRANSFORMER;

GRANT CREATE TABLE ON SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_ADMIN;
GRANT CREATE STAGE ON SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_ADMIN;
GRANT CREATE FILE FORMAT ON SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_ADMIN;

GRANT ROLE ERCOT_ADMIN TO USER AMON;
GRANT ROLE ERCOT_LOADER TO USER AMON;
GRANT ROLE ERCOT_TRANSFORMER TO USER AMON;
