
-- ERCOT Grid Pipeline — RAW schema grants for LOADER/TRANSFORMER
-- Run as ACCOUNTADMIN.
-- Note: stage READ grant for ERCOT_LOADER added separately once
-- the external stage is created (Step: storage integration + stage).


USE ROLE ACCOUNTADMIN;

-- Allow Airflow / ingestion script to load data into RAW tables
GRANT INSERT, DELETE ON ALL TABLES IN SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_LOADER;
GRANT INSERT, DELETE ON FUTURE TABLES IN SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_LOADER;

-- Allow dbt to read RAW data for transformations
GRANT SELECT ON ALL TABLES IN SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AWS_SNOWFLAKE_PIPELINE.RAW TO ROLE ERCOT_TRANSFORMER;
